//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.WCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pacientes", Namespace="http://schemas.datacontract.org/2004/07/WCFTransmissorMensagens.Models")]
    [System.SerializableAttribute()]
    public partial class Pacientes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomePacienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdPaciente {
            get {
                return this.IdPacienteField;
            }
            set {
                if ((this.IdPacienteField.Equals(value) != true)) {
                    this.IdPacienteField = value;
                    this.RaisePropertyChanged("IdPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomePaciente {
            get {
                return this.NomePacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NomePacienteField, value) != true)) {
                    this.NomePacienteField = value;
                    this.RaisePropertyChanged("NomePaciente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.ITransmissorMensagem")]
    public interface ITransmissorMensagem {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransmissorMensagem/InserirMensagem", ReplyAction="http://tempuri.org/ITransmissorMensagem/InserirMensagemResponse")]
        void InserirMensagem(WS.WCF.Pacientes pacientes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransmissorMensagem/InserirMensagem", ReplyAction="http://tempuri.org/ITransmissorMensagem/InserirMensagemResponse")]
        System.Threading.Tasks.Task InserirMensagemAsync(WS.WCF.Pacientes pacientes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransmissorMensagemChannel : WS.WCF.ITransmissorMensagem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransmissorMensagemClient : System.ServiceModel.ClientBase<WS.WCF.ITransmissorMensagem>, WS.WCF.ITransmissorMensagem {
        
        public TransmissorMensagemClient() {
        }
        
        public TransmissorMensagemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransmissorMensagemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransmissorMensagemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransmissorMensagemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InserirMensagem(WS.WCF.Pacientes pacientes) {
            base.Channel.InserirMensagem(pacientes);
        }
        
        public System.Threading.Tasks.Task InserirMensagemAsync(WS.WCF.Pacientes pacientes) {
            return base.Channel.InserirMensagemAsync(pacientes);
        }
    }
}
