//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pacientes", Namespace="http://schemas.datacontract.org/2004/07/WCFTransmissorMensagens.Models")]
    public partial class Pacientes : object
    {
        
        private System.Guid IdPacienteField;
        
        private string NomePacienteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdPaciente
        {
            get
            {
                return this.IdPacienteField;
            }
            set
            {
                this.IdPacienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomePaciente
        {
            get
            {
                return this.NomePacienteField;
            }
            set
            {
                this.NomePacienteField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.ITransmissorMensagem")]
    public interface ITransmissorMensagem
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransmissorMensagem/InserirMensagem", ReplyAction="http://tempuri.org/ITransmissorMensagem/InserirMensagemResponse")]
        System.Threading.Tasks.Task<bool> InserirMensagemAsync(WCF.Pacientes pacientes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface ITransmissorMensagemChannel : WCF.ITransmissorMensagem, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class TransmissorMensagemClient : System.ServiceModel.ClientBase<WCF.ITransmissorMensagem>, WCF.ITransmissorMensagem
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TransmissorMensagemClient() : 
                base(TransmissorMensagemClient.GetDefaultBinding(), TransmissorMensagemClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITransmissorMensagem.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransmissorMensagemClient(EndpointConfiguration endpointConfiguration) : 
                base(TransmissorMensagemClient.GetBindingForEndpoint(endpointConfiguration), TransmissorMensagemClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransmissorMensagemClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TransmissorMensagemClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransmissorMensagemClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TransmissorMensagemClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransmissorMensagemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> InserirMensagemAsync(WCF.Pacientes pacientes)
        {
            return base.Channel.InserirMensagemAsync(pacientes);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITransmissorMensagem))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITransmissorMensagem))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64286/TransmissorMensagem.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TransmissorMensagemClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITransmissorMensagem);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TransmissorMensagemClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITransmissorMensagem);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITransmissorMensagem,
        }
    }
}
